FROM python:3.11
WORKDIR /app

# Copy backend requirements and install
COPY ./backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend code
COPY ./backend/ .

EXPOSE 5000
CMD ["python", "app.py"]