FROM python:3.11

WORKDIR /app

# Copy requirements and install
COPY ./backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend
COPY ./backend/ ./backend/

# Copy frontend (VERY IMPORTANT)
COPY ./frontend/ ./frontend/

# Set working dir to backend
WORKDIR /app/backend

EXPOSE 5000

CMD ["python", "app.py"]