name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # Force Node.js 24 for deprecated actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend Docker image
        run: docker build -t security-log-analyzer-backend ./docker -f ./docker/Dockerfile-backend

      - name: Build frontend Docker image
        run: docker build -t security-log-analyzer-frontend ./docker -f ./docker/Dockerfile-frontend

      - name: List Docker images
        run: docker images